## Rest Client Test file
@baseUrl=http://localhost:4000/api
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjFkMjFkZi02ZThlLTRlNjktODg4OS05ZjIxNTQyMmIxMmUiLCJ1c2VyUm9sZSI6InVzZXIiLCJpYXQiOjE3NjU1NDIzMDcsImV4cCI6MTc2NTU0NTkwN30.eU_jRiHKoeketEe6JGigC4MNTcimRaVUqmHOP-h1bfg
### GET /health
GET {{baseUrl}}/health


### POST Register /auth/register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "toto",
  "email": "test@example.com",
  "password": "Test1234!",
  "confirmPassword": "Test1234!"
}

### POST Login /auth/login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "User123!"
}

### GET User Profile (Protected) /auth/me
GET {{baseUrl}}/auth/me
Authorization: Bearer {{accessToken}}

### POST Logout Profile /auth/logout
POST {{baseUrl}}/auth/logout

### DELETE Delete Profile /auth/me
DELETE {{baseUrl}}/auth/me

### PATCH Update Profile /auth/me
PATCH {{baseUrl}}/auth/me
Content-Type: application/json

{
  "username": "Fred",
  "last_name": "Dupont",
  "first_name": "Jean"
}