## Rest Client Test file
@baseUrl=http://localhost:3000/api
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhMGYyYzEyNC1kNzUyLTQzNTEtYTBjOS05MjE0MzBmMGIxMDkiLCJ1c2VyUm9sZSI6InVzZXIiLCJpYXQiOjE3NjUyNzExMDUsImV4cCI6MTc2NTI3NDcwNX0.19OL5cemYcAzH0hGem4tUPpoPUNGJMRDKW17x1tU0GA
### GET /health
GET {{baseUrl}}/health


### POST Register /auth/register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "toto",
  "email": "test@example.com",
  "password": "Test1234!",
  "confirmPassword": "Test1234!"
}

### POST Login /auth/login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Test1234!"
}

### GET User Profile (Protected) /auth/me
GET {{baseUrl}}/auth/me
Authorization: Bearer {{accessToken}}

### POST Logout Profile /auth/logout
POST {{baseUrl}}/auth/logout

### DELETE Delete Profile /auth/me
DELETE {{baseUrl}}/auth/me

### PATCH Update Profile /auth/me
PATCH {{baseUrl}}/auth/me
Content-Type: application/json

{
  "username": "Fred",
  "last_name": "Dupont",
  "first_name": "Jean"
}