@baseUrl=http://localhost:4000/api

### GET /books
GET {{baseUrl}}/books

### GET /books/:id
GET {{baseUrl}}/books/e6b8f93c-2a10-4f13-beb8-01ec8365c36c

### POST /books
POST {{baseUrl}}/books
Content-Type: application/json

{
  "isbn": "9782266111563",
  "title": "Mon Livre",
  "year": 2024,
  "summary": "Un résumé cool.",
  "language": "fr",
  "pages": 320,
  "image_url": "https://example.com/cover.jpg",
  "authors": [
    {
      "first_name": "Jean",
      "last_name": "Dupont"
    }
  ],
  "genres": [
    {
      "category": "Science Fiction"
    }
  ]
}


### PATCH /books/:id
PATCH {{baseUrl}}/books/c46cfede-5ab8-4aae-a8d8-e9aecded20b1
Content-Type: application/json  

{
  "title": "Mon Nouveau Livre",
  "pages": 350
}

### DELETE /books/:id
DELETE {{baseUrl}}/books/c46cfede-5ab8-4aae-a8d8-e9aecded20b1