@baseUrl=http://localhost:4000/api

POST {{baseUrl}}/contact
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "subject": "Hello from REST Client",
  "message": "This is a test message.\nSent from BlaBlaBook 📚."
}
